/**************************************************************************************

French language file (JO2)

***************************************************************************************/

fr_language = {
'Never miss an update!':'Ne manquez jamais une mise à jour!',
'This site uses cookies. if you enter, you will accept the use':"Ce site utilise des cookies. si vous entrez, vous acceptez l'utilisation",
'Listen an enjoy!':'Écoutez et profitez!',
'item(s)':'produit(s)',
'item(s) in cart':'produit(s) dans le panier',
'View cart':'Voir panier',
'Cart':'Panier',
'Filter by':'Filtrer par',
'Categories':'Catégories',
'Gender':'Sexe',
'Collections':'Collections',
'Select':'Sélectionner',
'Remove':'Supprimer',
'Men':'Homme ',
'Women':'Femme',
'Remember!':'Rappelez-vous!',
'Worldwide shipping':'Livraison dans le monde',
'Shipping at home':'Livraison à domicile',
'(Shippings...)':'(Livraison...)',
'Money return':'Satisfait ou remboursé',
'(100% Satisfaction...)':'(Satisfaction 100%...)',
'Secure payment':'Paiement sécurisé',
'(Payment methods...)':'(Modes de paiement...)',
'Doubts?':'Doutes?',
'(Contact us...)':'(Contactez-nous...)',
'Why choose us?':'Pourquoi nous choisir?',
'Your encrypted data travels between your computer and our server.':'Vos données sont cryptées entre votre ordinateur et notre serveur.',
'100% Satisfaction':'Satisfaction 100%',
'Money Back immediately in case of defect or loss.':'Satisfait ou remboursé immédiatement en cas de défaut ou de perte.',
'Home delivery':'Envoie à domicile',
'Our products are shipped directly to your home.':'Nos produits sont directement envoyés a votre domicile.',
'Personal attention':'Attention personelle',
'We have various communication channels for any concerns.':'Nous avons différents canaux de communication pour toutes les préoccupations.',
'Search...':'Recherche...',
'Site information':'Informations',
'Policies':'Politiques',
'Social media':'Réseaux sociaux',
'Home':"Page d'accueil",
'About us':'A propos de nous',
'Contact us':'Contactez-nous',
'Shipping and handling':'Frais de port et de manutention',
'Payment methods':'Modes de paiement',
'Satisfaction policy':'Politique de satisfaction',
'Legal notice':'Mentions légales',
'All right reserved':'Tous droits réservés',
'Powered by':'Propulsé par',
'Latest products':'Derniers produits',
'Enlarge':'Agrandir',
'See this collection':'Voir cette collection',
'Collection':'Collection',
'unit!':'unité!',
'units!':'unités!',
'Hurry up!':'Dépêchez-vous!',
'Sold out':'Epuisé',
'Price':'Prix',
'OFF':'DE MOINS!',
'Color':'Couleur',
'Size':'Taille',
'Qty':'Quant.',
'Quantity':'Quantité',
'For this product, the shipping cost is ':"Pour ce produit, le coût d'expédition est ",
'days approx. depending on the country':'jours environ. en fonction du pays',
'Your packet will be sent with tracking number if you order it on checkout.':'Votre paquet sera envoyé avec le numéro de suivi, si vous commandez sur votre bon de commande.',
'Refund in case of lost or defect. See our':'Remboursement en cas de perte ou de défaut. Voir notre',
'satisfaction policy.':'politique de satisfaction.',
'Do you have any question?':'Avez-vous une question?',
'Contact us!':'Contactez-nous!',
'Date: ':'Date: ',
'You might also like...':'Vous aimerez aussi...',
'Search with filter':'Recherche avec filtre',
'Checkout':'Caisse',
'Tracking number':'Numéro de suivi',
'Product':'Produit',
'Subtotal':'Sous-total',
"Navy blue":"Bleu foncé",
"Royal blue":"Bleu foncé",
"Deep blue":"Bleu foncé",
"Dark blue":"Bleu foncé",
"Light blue":"Azul clair",
"Turquoise":"Bleu turquoise",
"Khaki":"Kaki",
"Leopard":"Léopard",
"Blue":"Bleu",
"Green":"Vert",
"Dark green":"Vert foncé",
"Hunter green":"Vert foncé",
"Light green":"Vert clair",
"Yellow":"Jaune",
"Black":"Noir",
"Black and white":"Noir et blanc",
"Sky blue":"Bleu ciel",
"White":"Blanc",
"Brown":"Marron",
"Light brown":"Brun clair",
"Dark brown":"Marrón foncé",
"Mocha":"Moka",
"Purple":"Violet",
"Orange":"Orange",
"Gray":"Gris",
"Grey":"Gris",
"Light grey":"Gris clair",
"Dark grey":"Gris foncé",
"Light gray":"Gris clair",
"Dark gray":"Gris foncé",
"Coffee":"Café",
"Gold":"Or",
"Golden":"Or",
"Silver":"Argent",
"Red":"Rouge",
"Wine red":"Rouge vin",
"Light red":"Rouge clair",
"Dark red":"Rouge foncé",
"Pink":"Rose",
"Watermelon":"Rose",
"Light pink":"Rose clair",
"Dark pink":"Rosa foncé",
"Salmon":"Saumon",
"Apricot":"Abricot",
"Light pink":"Rose clair",
"Mustard":"Moutarde",
'Add to cart':'Ajouter au panier',
'Product added':'Produit ajouté',
'Management info':'Administration',
'SKU':'Ref.',
'Supplier':'Fournisseur',
'Posted by':'Publié par',
'Edit product':'Modifier produit',
'Stock':'Stock',
'See website':'Voir le site',
'Supplier price':'Prix de fournisseur',
'See the product':'Voir le produit',
'Profit':'Bénéfice',
'units':'unités',
'unit':'unité',
'Product weight':'Poids du produit',
'Thank you':'Merci!',
'Incorrect order':'Mauvais ordre',
'team':'Équipe',
'You have':'Vous avez',
'Subtotal in Cart':'SSous-total dans le panier',
'Shipping cost':'Coût de livraison',
'Paypal commission':'Commission de Paypal',
'Grand total':'Total',
'Get the tracking number of your order and stay calm!':'Obtenez le numéro de suivi de votre commande et de restez calme!',
'Select your country':'Choisissez votre pays',
'You can pay with credit card or PayPal':'Vous pouvez payer par carte de crédit ou PayPal',
'Your packet will be sent with tracking number if you order it':'Votre paquet sera envoyé avec numéro de suivi si vous commandez',
'Do you have any question?':'Avez-vous une question?',
'Place the order':"Placez l'ordre",
'The main questions that our customers have are':'Les principales questions de nos clients sont',
'How long does the delivery take?':'Combien de temps la livraison prend?',
'You can see this information in':'Vous pouvez voir cette information dans',
'What method of payment are there?':'Quelles méthodes de paiement sont-ils?',
'You can pay with credit card or PayPal. We accept Mastercard, Visa, Discover... The payment is secure and easy':'Vous pouvez payer par carte de crédit ou PayPal . Nous acceptons Mastercard , Visa, Discover ... Le paiement est sécurisé et facile',
'Where are we from?':'Où en sommes- nous de?',
'We are based in':'Nous sommes en',
'For everything else, you can contact us by':'Pour tout le reste , vous pouvez nous contacter par',
'E-mail':'E-mail',
'Telephone':'Téléphone',
'We will reply as soon as possible':'Nous vous répondrons dès que possible',
'Your order had an error. Please, try again or contact us.':"Votre commande a rencontré une erreur. S'il vous plaît, essayez à nouveau ou contactez-nous.",
'Success submission! Paypal will send you an automated e-mail notification for your reference. Please check your e-mail inbox for purchase order details and banking transaction options.':"Commande est terminée! Paypal vous enverra une notification par e-mail automatisé. S'il vous plaît vérifier votre boîte e-mail pour plus de détails d'ordre d'achat et des options de transaction bancaires.",
'Thank you again for your purchase!':'Merci encore de votre achat!',
'is a good online commercial company based in':'est une bonne société commerciale basé à',
'Our company has earned itself a solid reputation for quality, good service, reliability and professionalism in this field':"Notre société s'est forgé une solide réputation de qualité, bon service, la fiabilité et le professionnalisme dans ce domaine",
'Our operation capabilities cover favorable policy, instant and safe delivery, privacy protection and well-rounded customer support':"Nos capacités de fonctionnement couvrent politique favorable, la livraison instantanée et sûre, la protection de la vie privée et le soutien à la clientèle",
'The mission of':'La mission de',
'is to provide you with the best products to the best prices':'est de vous offrir les meilleurs produits au meilleur prix',
'Our reputation, experience and keen industry insight permit us to negotiate low prices on the net':"Notre réputation, l'expérience et perspicacité de l'industrie nous permettent de négocier à bas prix sur le net",
'If you have a suggestion you would like to share with our team, please let us know':"Si vous avez une suggestion que vous aimeriez partager avec notre équipe, s'il vous plaît laissez-nous savoir",
'Customer feedback shapes our business and allows us to better serve our audience so your ideas are always welcome':"Évaluations façonne notre entreprise et nous permet de mieux servir notre public. Vos idées sont toujours les bienvenus",
'respects your right to privacy':'respecte votre droit à la vie privée',
'Our goal is your complete satisfaction and we are not in the business of sharing your information with others':"Notre objectif est votre entière satisfaction et nous ne sommes pas dans l'entreprise de partager vos informations avec d'autres",
'All personal data is stored on our secure server with several layers of firewall protection':"Toutes les données personnelles sont stockées sur notre serveur sécurisé avec plusieurs couches de protection pare-feu",
'We promise to':'Nous promettons',
'Provide 24/7 customer support on weekdays':'Fournir un soutien continu',
'Streamline the buying and paying process':"Rationaliser le processus d'achat et de paiement",
'Deliver goods to our customers with speed and precision':'Expédition des produits rapidement et avec précision',
'Ensure the excellent quality of our products':"L'excellence dans la qualité des produits",
'We hope our customers get a great experience buying our products':"Nous espérons que nos clients obtiennent une grande expérience d'achat de nos produits",
'What shipping methods do you offer?':'Quels modes de livraison proposez-vous?',
'The order will be sent directly to your address':'La commande sera envoyé à votre adresse directement',
'The shipping method is':"La méthode d'expédition est",
'The shipping methods available are':"Les méthodes d'expédition disponibles sont",
'The delivery time is':'Le délai de livraison est',
'Flat rate shipping':'Expédition de taux forfaitaire',
'Standard rate shipping':'Expédition de taux standard',
'Expedited rate shipping':'Expédition de taux accéléré',
'days approx.':'jours environ.',
'The total shipping time is the order picking + handling time + shipping time':"Le temps total d'expédition est la préparation des commandes + temps de manipulation + temps d'expédition",
'Normally, the processing time is very low':'Normalement, le temps de traitement est très faible',
'The shipping time can vary depending on the country':'Le délai de livraison peut varier selon le pays',
'How do I calculate shipping costs?':"Comment puis-je calculer les frais d'expédition?",
'You will choose the shipping method on checkout':"Vous pouvez choisir la méthode d'expédition à la caisse",
'The shipping cost is':"le coût d'expédition est",
'regardless of the products you buy':'pour tous les produits que vous achetez',
'The shipping cost will vary depending the shipping method you select':"Le coût d'expédition varie en fonction de la méthode d'expédition que vous sélectionnez",
'You can see it on checkout':'Vous pouvez le voir à la caisse',
'The shipping cost will also vary depending on the weight of the products you add to cart':"Le coût d'expédition varie aussi en fonction du poids des produits que vous ajoutez au panier",
'How can I track my package?':"Comment puis-je vérifier l'état de ma commande?",
'If you choose the tracking number on checkout, you will get your tracking number and you will track':"Si vous choisissez le nombre de cheminement dans votre panier, vous verrez l'état de votre commande",
'Do you ship to my country?':"Pouvez-vous envoyer à mon pays?",
'Do not worry! We send to worldwide':"Ne vous inquiétez pas! Nous envoyons dans le monde entier",
'Actually we send to':"nous avons envoyé à",
'and':'et',
'If you do not find your county in the list, contact us':"Si vous ne voyez pas votre pays dans la liste, s'il vous plaît contactez-nous",
'If custom duties are incurred, who is responsible?':"Si les droits de douane sont engagés, qui est responsable?",
'It is the responsibility of the customer for any custom duty fees that may be charged upon delivery':"Il est de la responsabilité du client de tous les frais de droit de douane qui peuvent être imposés à la livraison",
'The import duty will depend of the custom policies of each country':"Le droit à l'importation dépendra des stratégies personnalisées de chaque pays",
'If the Package held by Customs, who will be responsible for Package clearance?':"Si le colis est tenu par des coutumes, qui va payer?",
'If the items are detained by Customs after the shipment is done, the buyer is responsible for clearance of the detained items':'Si le colis est tenu par des coutumes, le client sera responsable',
'How do I change my shipping address?':'Comment puis-je changer mon adresse de livraison?',
'If your order has been sent, you cannot change your shipping address. If the packet is not sent, contact us quickly':"Si votre commande a déjà été expédié, vous ne pouvez pas changer l'adresse. S'il n'a toujours pas été envoyé, contactez-nous rapidement",
'Shipping methods':"Méthodes d'expédition",
'Total weight':'Poids total',
'If your purchase is over':'Si votre achat est plus',
'your shipping will be free!':'votre expédition sera gratuit!',
'United States':'Etats-Unis',
'USA':'Etats-Unis',
'US':'Etats-Unis',
'China':'Chine',
'Japan':'Japon',
'Germany':'Allemagne',
'France':'France',
'United Kingdom':'Royaume-Uni',
'Brazil':'Brésil',
'Italy':'Italie',
'Russia':'Russie',
'India':'Inde',
'Canada':'Canada',
'Australia':'Australie',
'Spain':'Espagne',
'South Korea':'Corée du Sud',
'Mexico':'Mexique',
'Indonesia':'Indonésie',
'Netherlands':'Pays-Bas',
'Turkey':'Turquie',
'Switzerland':'Suisse',
'Sweden':'Suède',
'Poland':'Pologne',
'Belgium':'Belgique',
'Argentina':'Argentine',
'Austria':'Autriche',
'Thailand':'Thaïlande',
'South Africa':'Afrique du Sud',
'Venezuela':'Venezuela',
'Colombia':'Colombie',
'Denmark':'Danemark',
'Malaysia':'Malaisie',
'Singapore':'Singapour',
'Chile':'Chili',
'Hong Kong':'Hong Kong',
'Egypt':'Egypte',
'Philippines':'Philippines',
'Greece':'Grèce',
'Finland':'Finlande',
'Portugal':'Portugal',
'Ireland':'Irlande',
'Peru':'Pérou',
'Qatar':'Qatar',
'Ukraine':'Ukraine',
'New Zealand':'Nouvelle-Zélande',
'Romania':'Roumanie',
'Hungary':'Hongrie',
'Puerto Rico':'Puerto Rico',
'Morocco':'Maroc',
'Ecuador':'Equateur',
'Cuba':'Cuba',
'Croatia':'Croatie',
'Luxembourg':'Luxembourg',
'Guatemala':'Guatemala',
'Uruguay':'Uruguay',
'Andorra':'Andorre',
'How can I pay?':"Comment puis-je payer?",
'You can pay on checkout when you add your product to shopping cart. We have two methods: Credit card and Paypal':"Vous pouvez payer à la caisse Lorsque vous ajoutez votre produit au panier. Nous avons deux méthodes: par carte de crédit et Paypal",
'What credit cards do we accept?':'Quelles cartes de crédit acceptons-nous?',
'We accept the credit cards most used':'Nous acceptons les cartes de crédit les plus utilisées',
'Mastercard, Visa, American Express, Discover and Aurora':'Mastercard, Visa, American Express, Discover et Aurora',
'What advantages do I have if I pay with paypal?':"Quels avantages ai-je si je paye avec paypal?",
'You can get many advantages':'Vous pouvez obtenir de nombreux avantages',
'Secure system and secure payments, buy and pay with your mobile or tablet, no membership fees or service charges, discount coupons':'Système de paiement sûr et sécurisé, acheter et payer avec votre téléphone ou tablette, pas de commissions, des coupons de réduction',
'We will try our best to make sure the products shipped to our customers are in good quality':"Nous ferons de notre mieux pour s'assurer que les produits expédiés à nos clients sont de bonne qualité",
'If there are some problems on the goods, you have right to guarantee your benefits':"S'il ya des problèmes sur les marchandises, vous avez droit à la garantie de vos prestations",
'You do not have to worry about anything!':"Vous n'avez pas à vous soucier de quoi que ce soit!",
'Return and refund':'Retour du produit et le remboursement',
'The products with quality problem can be returned and refund':"Produits avec des problèmes de qualité peuvent être retournés et remboursés",
'The customer will need to send the products back to us':'Le client devra envoyer le produit',
'When we receive the products, we will give the refund':'Lorsque nous recevons les produits, nous donnerons le remboursement',
'Loss':'Perte',
'If your packet has been sent but you do not receive the packet, the problem is the carrier':"Si votre paquet a-été envoyée, mais vous ne recevez pas le paquet, le problème est le transporteur",
'But we want to have satisfied customer':'Mais nous voulons des clients satisfaits',
'For that, if your packet is lost, we will refund your money or we will send again':"Pour cela, si votre paquet est perdu, nous vous rembourserons votre argent ou nous enverrons à nouveau",
'Products with quality problem can be returned and replaced':'Produits avec des problèmes de qualité peuvent être retournés et remplacés',
'Customer need to send the products back to us':'Le client doit envoyer le paquet',
'When we receive the products, we will replace new ones and ship back to customer':'Lorsque nous obtenons le paquet, nous remplacerons et réexpédier',
'Replace':'Remplacement',
'1.- INTRODUCTION':'1.- INTRODUCTION',
'This document is intended to establish and regulate the terms of use and safeguarding the data of the site':"Ce document est destiné à établir et réglementer les conditions d'utilisation et la sauvegarde du Site",
'(from now on called “the Site”) understanding that the site has all the pages and contents owned by':"(ci-après le «Site») entendue comme l'ensemble des pages et son contenu appartenant",
'which is accessed through the domain':'à laquelle on accède par le domaine',
'The use of this site as well as the services it offers to the user, implies full and unreserved acceptance of each and every one of the conditions contained in this Legal Notice (from here on "General Conditions ")':"L'utilisation de ce site ainsi que des services offerts à l'utilisateur, implique l'acceptation pleine et entière de toutes et chacunes des conditions contenues dans le présent avis juridique (ci-après les «Conditions générales »)",
'so the user should be aware of the importance of reading them each time the user visits the Site':"ainsi que l'utilisateur doit être conscient de l'importance de la lecture à chaque fois que vous visitez le site",
'Accessing the Site implies knowing and  accepting the following "General Conditions" which':"L'accès au Site implique la connaissance et l'acceptation des conditions générales suivantes, lesquelles",
'recommends the users to print or download and read  carefully each time the user accesses the Site':"recommande aux utilisateurs d'imprimer ou de les télécharger et les lire attentivement chaque fois que vous accédez au Site",
'2.-GENERAL INFORMATION':'2.- INFORMATION GÉNÉRAL',
'In compliance with the duty to inform the customer contained in Article 10 of Law 34/2002, of July 11, of the Society Services of the Information  and Electronic Commerce, below we reflect the following':"En conformité avec les obligations de déclaration prévues à l'article 10 de la loi 34/2002, du 11 Juillet, la Société des Services d'Information et le Commerce Électronique, ci-dessous reflètent les éléments suivants",
'is an entity from':'est une entité dans',
'The email contact is':'Le contact e-mail est',
'and the telephone':'et le téléphone',
'3. - USE OF THE SITE':"3. - CONDITIONS D'UTILISATION DU SITE",
'By accepting these Terms the user agrees to use the Website and the services it provides in the way, the manner and form in which it is established':"En acceptant ces conditions, vous acceptez d'utiliser le Site et les services qu'il fournit dans le chemin, dans la manière et la forme dans laquelle il est établi",
'Users may not use this Site and its services for illegal and / or contrary purposes against those  stated in the General Conditions, which may be detrimental to the rights and / or interests of others or in any way damage the Site preventing it or its present and future services to work':"Les utilisateurs ne peuvent pas utiliser ce Site et de ses services pour les contenus illicites et / ou contraires aux buts énoncés dans ces Termes et Conditions, ce qui peut être préjudiciable aux droits et / ou intérêts d'autrui ou tout endommagement du site Web ou de son mal fonctionement ou des services qu'il offre ou offerts à l'avenir.",
'4.- SCOPE OF THE SITE. USER RESPONSIBILITY':"4.- CHAMP D'APPLICATION DU SITE. RESPONSABILITE DE L'UTILISATEUR",
'The access to this site is the sole responsibility of the users. That includes any risks arising from the use of the Site':"L'accès à ce site est de la seule responsabilité des utilisateurs. Les risques découlant de l'utilisation du site par l'utilisateur relève de la responsabilité unique et exclusive",
'does NOT guarantee':'Pas sous garantie par',
'(I) The infallibility, availability, continuity, absence of defects or safety of the Site':"(I) l'infaillibilité, la disponibilité, la continuité, l'absence de défauts ou la sécurité du Site",
'(II) The content of the Site or the information passing through it are free of viruses or other harmful elements such as errors, omissions or inaccuracies':"(II) le contenu du site ou de l'information qui le traverse sont exempts de virus ou autres éléments nocifs tels que les erreurs, omissions ou inexactitudes",
'(III) The safety of the user of the Website; The size not be liable for any loss or damage that may arise from interferences, omissions, interruptions, computer viruses, telephone faults or disconnections in the operational functioning of this electronic system , due to causes unrelated to the Site, the delays or blockages in the use of this electronic system caused by deficiencies or overloading in the data processing Centre, telephone lines, in the Internet system or other electronic systems, nor damage that may be caused by third parties through illegalities beyond the control of the Site':"(III) l'utilisation sûre que l'utilisateur fais du site Web; Le Site ne peut être tenu responsable de toute perte ou dommage pouvant découler d'interférences, omissions, interruptions, virus informatiques, pannes téléphoniques ou déconnexions dans le fonctionnement opérationnel de ce système électronique , en raison de causes non liées à la marque d'Ivoire, retards ou blocages dans l'utilisation de ce système électronique causés par des déficiences ou des surcharges dans le Centre de traitement des données, des lignes téléphoniques, du système Internet ou d'autres systèmes électroniques, ni dommages qui peuvent être causés par des tiers par le biais illégale en dehors du contrôle de le Site",
'It also exempts the Site from liability for any loss or damage incurred by you as a result of errors, defects or omissions in the information provided by the Site provided from outside sources':"Il dispense également dans le Site de toute responsabilité pour toute perte ou dommage subi par vous en raison d'erreurs, de défauts ou omissions dans l'information fournie par le Site aporté par des sources extérieures",
'Mere access to the Site does not imply any kind of commercial relationship between the user and the Site':"Le simple accès au Site n'implique aucune sorte de relation commerciale entre l'utilisateur et le Site",
'5.- UPDATING AND MODIFICATION OF INFORMATION':'5.- ACTUALITÉ ET MODIFICATION DES INFORMATIONS',
'The information on this site is accurate at the date of the last update. The Site reserves the right to update, modify or delete information on this Site, and may limit or deny access. The Site reserves the right to make, at any time, changes and modifications deemed desirable, and may exercise this right at any time and without notice':"Les informations sur ce site sont exactes à la date de la dernière mise à jour. le Site se réserve le droit de mettre à jour, modifier ou supprimer des informations sur ce site, et peut limiter ou refuser l'accès. Le Site se réserve le droit d'apporter, à tout moment, les changements et les modifications jugées souhaitables, peuvent exercer ce droit à tout moment et sans préavis",
'6.- CONTENTS':'6.- CONTENU',
'The Site does not guarantee, or accepts responsibility for the consequences that may result from errors in the contents appearing on the Site provided by others. The Site is not responsible in any way for the contents, commercial activities, products and services that can be viewed through electronic links (links) if there were any, and if there were, directly or indirectly, through this Site':"Le Site ne garantit pas, ou n'accepte aucune responsabilité pour les conséquences qui pourraient résulter d'erreurs dans les contenus affichés sur le site Web fourni par d'autres. Le Site n'est pas responsable en aucune façon pour les contenus, activités commerciales, produits et services qui peuvent être consultés par des liens électroniques (links), directement ou indirectement, par le biais de ce site",
'The presence of links in the the Site Website, unless expressly stated otherwise, is for informational purposes only and in no way a suggestion, invitation or recommendation thereof. These links do not represent any kind of relationship between the Site and companies or owners of the websites that can be accessed through these links. The Site reserves the right to withdraw unilaterally and at any time and without notice the link from its Site':"Les liens dans le site Web, sauf mention contraire expresse, à titre d'information seulement et en aucun cas un de ses suggestion, invitation ou recommandation. Ces liens ne représentent aucun type de relation entre le Site et des sociétés ou propriétaires de sites Web qui peuvent être accessibles via ces liens. Le Site se réserve le droit de retirer unilatéralement et à tout moment et sans préavis les liens qui pouraient apparaître sur son site Web",
'The Site reserves the right to prevent or prohibit access to the Site to any Internet user to enter this site any content contrary to legal or moral standards, reserving the right to pursue legal action it deems necessary to prevent such behaviours':"Le Site se réserve le droit d'empêcher ou d'interdire l'accès au Site à tout utilisateur d'Internet à accéder à ce site tout contenu contraire aux normes juridiques ou morales, en se réservant le droit d'engager des poursuites judiciaires qu'il jugera nécessaires pour empêcher un tel comportements",
'7.- NAVIGATION, ACCESS AND SECURITY':'7.- NAVEGATION, ACCÈS ET SECURITÉ',
'The Site Central makes every effort to ensure that browsing takes place under optimum conditions and to avoid any type of damage that may occur during the same. The Site is not liable for damages of any kind that may be caused to users by using other browsers or different versions of the browsers for which the Site is designed':"Le Site met tout en œuvre pour que la navigation s'effectue dans des conditions optimales et d'éviter tout type de dommages qui pourraient survenir au cours de la même chose. Le Site n'est pas responsable des dommages de toute nature qui pourraient être causés aux utilisateurs à l'aide d'autres navigateurs ou des versions différentes des navigateurs pour lesquels le site a été conçu",
'The Site makes no representation or guarantee that access to this Site will be uninterrupted or error free. No responsibility or guarantee that the content or software that can be accessed through this site is free from error or cause damage. The Site, in no event, can be liable for any losses or damages of any kind arising from the access and use of the Site, including but not limited to damage to systems or those caused by a virus':"Le Site ne se fait pas résponsable ni garantie que l'accès à ce Site sera ininterrompu ou exempt d'erreur. Aucune responsabilité ou garantie que le contenu ou les logiciels qui peuvent être accessibles via ce site est exempte d'erreur ou causer des dommages. En aucun cas, le Site doit être tenu responsable de toute perte ou dommages de toute nature résultant de l'accès et de l'utilisation du Site, y compris, mais sans s'y limiter, les dommages causés aux systèmes ou ceux qui sont causés par un virus. Le Site n'est pas responsable des dommages qui pourraient être causés aux usagers par une mauvaise utilisation de ce site. En particulier, n'est pas responsable en aucune façon pour les pannes, interruptions, défauts dans les télécommunications qui peuvent survenir",
'The Site is not responsible for any damage that may be caused to users by improper use of this Site. In particular, is not responsible in any way for breakdowns, interruptions, faults or defects in telecommunications that may occur. The services offered on the Site may only be used correctly if they meet the technical specifications for which it was designed':"Les services proposés sur le Site ne peut être utilisé correctement si elles répondent aux spécifications techniques pour lesquelles il a été conçu",
'8.- DATA PROTECTION':'8.- PROTECTION DES DONNÉES',
'The processing of personal data and sending electronic communications are regulated by  the rules established in the Organic Law':"Le traitement des données personnelles et l'envoi de communications électroniques sont adaptées aux règles établies dans Loi organique",
'In accordance with the provisions of the current legislation on data protection, we inform you that your personal data will be incorporated into the Site Personnel Selection file in order to have your professional history for selection and contractual purposes':"En conformité avec les dispositions de la législation actuelle sur la protection des données, nous vous informons que vos données personnelles seront incorporées dans le fichier du personnel dans le Site afin d'avoir vos antécédents professionnels pour développer et sélectionner les fonctions de recrutement",
'Also, unless stated otherwise, the Site and any of the Companies that make up the Site, shall have access to your personal information, solely for the purposes described above. The Site guarantees the right to access, rectify, cancel and object to the processing of data which must be notified in writing':"En outre, sauf disposition expresse à ce sujet des objets, doivent avoir accès à vos renseignements personnels les sociétés qui font partie dans le Site, exclusivement aux fins décrites ci-dessus. le Sote garantit l'exercice des droits d'accès, rectification, annulation et opposition en écrivant",
'If after one year from the inclusion of your personal data you have not heard from us, we will proceed to erase the data from our file':"Si au bout d'un an à compter de la prise en compte de votre CV vous n'avez pas reçue de nos nouvelles, nous procéderons à effacer vos données de notre fichier",
'9.- USE OF COOKIES':"9.- SUR L'UTILISATION DES COOKIES",
'Access to the Website may imply the use of cookies on its pages and those pages linked or referenced through links. Users who do not wish to receive cookies or want to be informed of their use may configure your browser accordingly':"L'accès à ce site peut impliquer l'utilisation de cookies sur ses pages et ces pages liées ou référencées par des liens. Les utilisateurs qui ne souhaitent pas recevoir de cookies ou si vous voulez être informés de leur utilisation peuvent configurer votre navigateur en conséquence",
'10.- INTELLECTUAL PROPERTY AND COPYRIGHT':"10.- PROPRIÉTÉ INTELLECTUELLE ET DROIT D'AUTEUR",
'The Site declares that unless otherwise indicated in the Site, text, images, illustrations, designs, icons, photographs, video clips, sound clips and other materials found on the Site and any other intellectual creations and / or inventions or scientific and technical discoveries, whatever their commercial or industrial application (from here on  collectively named "Content") have been created or invented by the Site or transferred, licensed, transmitted or authorized by the owners and / or assignees':"Le Site déclare que, sauf indication contraire dans le site, textes, images, illustrations, dessins, icônes, photos, clips vidéo, clips audio et d'autres matériaux trouvés sur le site, et toutes autres créations intellectuelles et / ou inventions ou découvertes scientifiques et techniques, quelle que soit leur application commerciale ou industrielle (ci-après dénommés collectivement le «Contenu») sont créés ou inventés par le Site ou d'une licence, transmis ou autorisés par les propriétaires et / ou ayants droit",
'The User agrees not to remove or alter any distinctive sign used on the Site, including, but not be limited, brand names, trademarks (graphics, logos, etc), the "copyright" and other data identifying the rights of the Site or third parties on the Website':"L'Utilisateur s'engage à ne pas supprimer ou modifier tout signe distinctif utilisé sur le Site, y compris, mais sans s'y limiter, les noms de marque, marques (graphiques, logos, etc), le copyright et autres données d'identification des droits dans le Site ou par des tiers sur le site",
'The Site own all rights over any works, inventions, discoveries, patents, ideas, concepts, updates and improvements related to the Site,  systems, applications and programs or services provided by the Site, which are created , made, developed or implemented first by the Site either alone or with the help of users of the Site, during or as a result of a design, development or other activity performed in accordance with the Contract':"Le Site a la propriété et tous les droits sur les œuvres, inventions, découvertes, brevets, idées, concepts, mises à jour et les améliorations liées au site, vos systèmes, des applications et des programmes ou des services fournis par le Site, qui sont créés , réalisés, développés ou mis en œuvre d'abord par le Site, seul ou avec l'aide des utilisateurs du site, au cours ou à la suite d'une conception, le développement ou autre activité réalisée en conformité avec le contrat",
'You may not use the name, trademarks, symbols, logos or distinctive signs of ownership by the Site without the express written consent of the latter':"Vous ne pouvez pas utiliser le nom, les marques, symboles, logos ou signes distinctifs de la propriété par le Site sans l'autorisation écrite expresse de ce dernier",
'In the event that any user or third party considers that any of the content on the site is in violation of copyright or other rights of intellectual property protection, please notify us at':"Dans le cas où un utilisateur ou un tiers considère que tout le contenu sur le site est en violation du droit d'auteur ou autres droits de protection de la propriété intellectuelle, s'il vous plaît nous en informer à l'adresse",
'11.- JURISDICTION AND LAW':'11.- COMPETENCE ET DROIT APPLICABLE',
'The Terms of Use that are in this Agreement are governed by law. Both the Site and the users of the Site agree that any dispute that may arise regarding the interpretation, compliance and / or enforcement of these rules shall be subject to the jurisdiction of the Courts and Tribunals , with expressly waive any other jurisdiction that may correspond':"Les conditions d'utilisation qui sont dans le présent accord sont régies par la loi espagnole. Le Site à la fois comme utilisateurs du site acceptent que tout litige qui pourrait survenir concernant l'interprétation, de la conformité et / ou l'application de ces règles est soumis à la juridiction des Cours et Tribunaux et renoncent expressément à toute autre juridiction qui pourrait lui correspondre",
'Euro':'Euro',
'US dollar':'Dollar des États-Unis',
'Pound sterling':'Livre sterling',
'Management':'Administration',
'Product in stock':'Produit disponible',
'Create product':'Créez produit',
'Overview':"Vue d'ensemble",
'Products':'Produits',
'Pages':'Pages',
'Stats':'Statistiques',
'Layout':'Disposition',
'Template':'Gabarit',
'Settings':'Configuration',
'Images':'Images',
'Sign out':'Déconnexion',
'Prev':'Précédent',
'Next':'Suivant',
'Name':'Nom',
'Email':'Email',
'Message':'Message',
'Send':'Envoyer',
'Please, insert a correct email':"S'il vous plaît, fournir une adresse email correcte",
'Please, write a message':"S'il vous plaît , écrivez un message",
'Your message has been sent. Thanks!':"Votre message a été envoyé . Merci!",
'Through the following contact form':'Grâce à le formulaire de contact ci-dessous',
'Edit notes':'Modifier les notes',
'Unique size':'Taille unique',
'One size':'Taille unique',
'Accessories':'Accessoires',
'Bags backpacks and wallets':'Sac a main, sac a dos et portefeuilles',
'Corsets and bustiers':'Corsets et bustiers',
'Dresses':'Vêtements',
'Heels boots and sandals':'Talons, bottes et sandales',
'Jackets and coats':'Vestes et manteaux',
'Leggings and pantyhose':'Leggings et collants',
'Pants and jeans':'Pantalons et jean',
'Shirts polo shirts and blouses':'Chemises, chemises polos et chemisiers',
'Shoes and sneakers':'Chaussures et chaussures de tennis',
'Skirts':'Jupes',
'Suits and blazers':'Costumes et blazers',
'Sweaters and hoodies':'Pull et sweats',
'Tees long sleeves and tops':'T-shirts de manche courte, longue et sans manche',
"Main dh diamond horn tee":"T-shirt main dh diamond horn",
"Sexy girl diamond horn tee":"T-shirt sexy girl diamond horn",
"Audio cassette diamond horn tee":"T-shirt audio cassette diamond horn",
"Tees; long sleeves and tops":"T-shirts de manga corta; larga y asillas",
"MMA division tee":"T-shirt MMA division",
"Defeat thy rivals tee":"T-shirt Defeat thy rivals",
"Extreme cage fighter tee":"T-shirt Extreme cage fighter",
"Mixed marcial arts tee":"T-shirt Mixed marcial arts",
"Training to be a cage fighter tee":"T-shirt Training to be a cage fighter",
"MMA fighter tee":"T-shirt MMA fighter",
"Mixed marcial arts tee":"T-shirt Mixed marcial arts",
"Cage fighter tee":"T-shirt Cage fighter",
"Bushido MMA tee":"T-shirt Bushido MMA",
"Brooklyn boxing gym tee":"T-shirt Brooklyn boxing gym",
"Bojewoje sambo tee":"T-shirt Bojewoje sambo",
"Mma Full contact fighter warriors long sleeves":"T-shirt de manga larga Mma Full contact fighter warriors",
"New zealand all black long sleeves":"T-shirt de manga larga New zealand all black",
"Rugby athletic train long sleeves":"T-shirt de manga larga Rugby athletic train",
"Hardcore cage fighting long sleeves":"T-shirt de manga larga Hardcore cage fighting",
"Cage fighter mma fight to the end tee":"T-shirt Cage fighter mma fight to the end",
"Mma fight division bulldog tee":"T-shirt Mma fight division bulldog",
"Muay thai the art of fighting tee":"T-shirt Muay thai the art of fighting",
"Mma fighter warrior spirit tee":"T-shirt Mma fighter warrior spirit",
"Mixed marcial arts fight with honor tee":"T-shirt Mixed marcial arts fight with honor",
"Mma fighter training discipline respect tee":"T-shirt MMA fighter training discipline respect",
"Jiu jitsu red cover tee":"T-shirt Jiu jitsu red cover",
"Cage fighter don't give up the fighter tee":"T-shirt Cage fighter don't give up the fighter",
"Mma fighters tee":"T-shirt MMA fighters",
"Full contact mma tee":"T-shirt Full contact MMA",
"Full contact mixed martial arts tee":"T-shirt Full contact mixed martial arts",
"Muay thai full contact tee":"T-shirt Muay thai full contact",
"Hard knocks boxing gym tee":"T-shirt Hard knocks boxing gym",
"Born 2 be a boxer tee":"T-shirt Born 2 be a boxer",
"Invincible tee":"T-shirt Invincible",
"Jiu-jitsu tee":"T-shirt Jiu-jitsu",
"MMA Mixed marcial arts tee":"T-shirt MMA Mixed marcial arts",
"Urban fighters tee":"T-shirt Urban fighters",
"Ultimate fight dept. tee":"T-shirt Ultimate fight dept.",
"Seek and destroy tee":"T-shirt Seek and destroy",
"Rocky balboa boxing gym tee":"T-shirt Rocky balboa boxing gym",
"Primus pilus mma tee":"T-shirt Primus pilus MMA",
"The newspaper tee":"T-shirt The newspaper",
"Muay thai boxing tee":"T-shirt Muay thai boxing",
"This store is configured to be able to purchase and ship your items to somewhere in the world. Do you live in US, Brazil, Australia, Europe...? Are you going on vacation and you want it delivered? No Problem! We'll send it!":"Le web est mis à acheter et expédier votre produit partout dans le monde. Vivez-vous au Canada, en France, en Amérique latine? Allez-vous partir en vacances et que vous souhaitez le recevoir? Pas de problème! Nous l'enverrons.",
"Use our shipments!":"Utilisez nos envois!",
"Don't risk!":"Ne vous décevra pas!",
"We have the best satisfaction policy. If your packet is lost or you receive a defective product, we will refund your money immediately. Don't risk buying at other stores and losing your money. Here your order is secure. Try it!":"Ce magasin a la meilleure politique de satisfaction. Si votre colis est perdu ou a reçu un produit défectueux, nous vous rembourserons immédiatement l'argent. Ne pas le risque d'acheter d'autres magasins et de gaspiller votre argent. Ici, votre commande est sécurisée. Essayez-le!",
"Not disappoint!":"Il ne suce pas!",
"The best spanish brand: 'Diamond horn'":"La marque espagnole: 'Diamond horn'",
"We are glad for to present you a cool clothing brand: 'Diamond horn'. They bring a magnific collection of nice products. We are the only one authorized dealer. You will not find these products anywhere else. Are you going to let it go?":"Nous sommes fiers de présenter une marque de vêtements: 'Diamond Horn'. Ils nous apportent une magnifique collection de très bons produits. Nous sommes les distributeurs autorisés. Vous ne trouverez pas ces produits ailleurs. Allez-vous le laisser aller?",
"Take advantage!":"Ne manquez pas l'occasion!",
"Page not found":"Page non trouvée",
"You will be redirected to the homepage.":"Vous serez redirigé vers la page d'accueil.",
"No results":"Aucun résultat",
"Description":"Description",
"Category":"Catégorie",
"Brand":"Marque",
"Features":"Caractéristiques",
"Type":"Type",
"Colors":"Couleurs",
"Empty cart":"Vide panier",
"Specifications":"Caractéristiques"
}
