/**************************************************************************************

Spanish language file (JO2)

***************************************************************************************/

es_language = {
'Never miss an update!':'¡No te pierdas nada!',
'This site uses cookies. if you enter, you will accept the use':'Este sitio usa cookies. Si entras, aceptas el uso',
'Listen an enjoy!':'¡Escucha y disfruta!',
'item(s)':'producto(s)',
'item(s) in cart':'producto(s) en el carrito',
'View cart':'Ver el carrito',
"Cart":"Carrito",
'Filter by':'Filtrar por',
'Categories':'Categorías',
'Gender':'Género',
'Collections':'Colecciones',
'Select':'Selecciona',
'Remove':'Eliminar',
'Men':'Hombre',
'Women':'Mujer',
'Remember!':'¡Recuerda!',
'Worldwide shipping':'Envío a todo el mundo',
'Shipping at home':'Envío a casa',
'(Shippings...)':'(Envíos...)',
'Money return':'Devolución del dinero',
'(100% Satisfaction...)':'(Satisfacción 100%...)',
'Secure payment':'Pago seguro',
'(Payment methods...)':'(Métodos de pago...)',
'Doubts?':'¿Tienes dudas?',
'(Contact us...)':'(Contáctanos...)',
'Why choose us?':'¿Por qué elegirnos?',
'Your encrypted data travels between your computer and our server.':'Tus datos encriptados viajan entre tu ordenador y nuestro servidor.',
'100% Satisfaction':'Satisfacción 100%',
'Money Back immediately in case of defect or loss.':'Devolución del dinero inmediata en caso de defecto o pérdida.',
'Home delivery':'Envío a casa',
'Our products are shipped directly to your home.':'Nuestros productos se te envían directamente a casa.',
'Personal attention':'Atención directa',
'We have various communication channels for any concerns.':'Disponemos de varios canales de comunicación para cualquier cuestión.',
'Search...':'Buscar...',
'Site information':'Información',
'Policies':'Políticas',
'Social media':'Medios sociales',
'Home':'Inicio',
'About us':'Sobre nosotros',
'Contact us':'Contacto',
'Shipping and handling':'Envío y manejo',
'Payment methods':'Métodos de pago',
'Satisfaction policy':'Política de satisfacción',
'Legal notice':'Aviso legal',
'All right reserved':'Todos los derechos reservados',
'Powered by':'Con tecnología',
'Latest products':'Últimos productos',
'Enlarge':'Maximizar',
'See this collection':'Ver esta colección',
'Collection':'Colección',
'unit!':'unidad!',
'units!':'unidades!',
'Hurry up!':'¡Date prisa!',
'Sold out':'Agotado',
'Price':'Precio',
'OFF':'MENOS',
'Color':'Color',
'Quantity':'Cantidad',
'For this product, the shipping cost is ':'Para este producto, el coste de envío es ',
'days approx. depending on the country':'días aprox. dependiendo del país',
'Your packet will be sent with tracking number if you order it on checkout.':'Su paquete será enviado con número de seguimiento si lo pides en el carrito.',
'Refund in case of lost or defect. See our':'Devolución en caso de pérdida o defecto. Mira nuestra',
'satisfaction policy.':'política de satisfacción.',
'Do you have any question?':'¿Alguna pregunta?',
'Contact us!':'¡Contáctanos!',
'Date: ':'Fecha: ',
'You might also like...':'También podría gustarte...',
'Search with filter':'Búsqueda con filtro',
'Checkout':'Carrito',
'Tracking number':'Número de seguimiento',
'Product':'Producto',
'Color':'Color',
'Size':'Talla',
'Qty':'Cant.',
'Subtotal':'Subtotal',
'Royal blue':'Azul oscuro',
'Navy blue':'Azul oscuro',
'Deep blue':'Azul oscuro',
'Dark blue':'Azul oscuro',
'Light blue':'Azul claro',
'Turquoise':'Azul turquesa',
'Khaki':'Caqui',
'Leopard':'Leopardo',
'Blue':'Azul',
'Green':'Verde',
'Army green':'Verde',
'Dark green':'Verde oscuro',
'Hunter green':'Verde oscuro',
'Light green':'Verde claro',
'Yellow':'Amarillo',
'Black':'Negro',
'Black and white':'Blanco y negro',
'Sky blue':'Azul celeste',
'White':'Blanco',
'Brown':'Marrón',
'Light brown':'Marrón claro',
'Dark brown':'Marrón oscuro',
'Mocha':'Moca',
'Purple':'Violeta',
'Orange':'Naranja',
'Gray':'Gris',
'Grey':'Gris',
'Light grey':'Gris claro',
'Dark grey':'Gris oscuro',
'Light gray':'Gris claro',
'Dark gray':'Gris oscuro',
'Coffee':'Color café',
'Gold':'Dorado',
'Golden':'Dorado',
'Silver':'Plateado',
'Red':'Rojo',
'Wine red':'Rojo vino',
'Light red':'Rojo claro',
'Dark red':'Rojo oscuro',
'Pink':'Rosa',
'Watermelon':'Rosa',
'Light pink':'Rosa claro',
'Dark pink':'Rosa oscuro',
'Salmon':'Salmón',
'Apricot':'Albaricoque',
'Light pink':'Rosa claro',
'Mustard':'Mostaza',
'Add to cart':'Añadir al carrito',
'Product added':'Producto añadido',
'Management info':'Administración',
'SKU':'Ref.',
'Supplier':'Proveedor',
'Posted by':'Subido por',
'Edit product':'Editar producto',
'Stock':'Stock',
'See website':'Ver web',
'Supplier price':'Precio de proveedor',
'See the product':'Ver el producto',
'Profit':'Ganancia',
'units':'unidades',
'unit':'unidad',
'Product weight':'Peso del producto',
'Thank you':'¡Gracias!',
'Incorrect order':'Pedido incorrecto',
'team':'Equipo',
'You have':'Tienes',
'Subtotal in Cart':'Subtotal del carrito',
'Shipping cost':'Coste de envío',
'Paypal commission':'Comisión de Paypal',
'Grand total':'Total',
'Get the tracking number of your order and stay calm!':'Obtén el número de seguimiento de tu pedido y ¡mantén la calma!',
'Select your country':'Selecciona tu país',
'You can pay with credit card or PayPal':'Puedes pagar con tarjeta de crédito o Paypal',
'Your packet will be sent with tracking number if you order it':'Tu paquete será enviado con número de seguimiento si lo pides',
'Do you have any question?':'¿Alguna pregunta?',
'Place the order':'Realizar el pedido',
'The main questions that our customers have are':'Las principales preguntas que nuestros clientes tienen son',
'How long does the delivery take?':'¿Cuánto tiempo tarda el envío?',
'You can see this information in':'Puedes ver esta información en',
'What method of payment are there?':'¿Qué metodos de pago hay?',
'You can pay with credit card or PayPal. We accept Mastercard, Visa, Discover... The payment is secure and easy':'Puedes pagar con tarjeta de crédito o Paypal. Aceptamos Mastercard, Visa, Discover... El pago es seguro y muy fácil',
'Where are we from?':'¿De donde somos?',
'We are based in':'Nuestra sede se ubica en',
'For everything else, you can contact us by':'Para todo lo demás, puedes ponerte en contacto con nosotros por',
'E-mail':'E-mail',
'Telephone':'Teléfono',
'We will reply as soon as possible':'Te responderemos lo más rápido posible',
'Your order had an error. Please, try again or contact us.':'Tu pedido ha tenido un error. Por favor, intenta realizarlo otra vez o contacta con nosotros.',
'Success submission! Paypal will send you an automated e-mail notification for your reference. Please check your e-mail inbox for purchase order details and banking transaction options.':'¡Pedido completado! Paypal te enviará un mensaje automático. Por favor, comprueba tu correo para ver los detalles de tu pedido.',
'Thank you again for your purchase!':'¡Gracias nuevamente por tu compra!',
'is a good online commercial company based in':'es una gran compañía comercial online con sede en',
'Our company has earned itself a solid reputation for quality, good service, reliability and professionalism in this field':'Nuestra compañía se ha ganado una sólida reputación por la calidad, buen servicio y profesionalidad en este campo',
'Our operation capabilities cover favorable policy, instant and safe delivery, privacy protection and well-rounded customer support':'Nuestra capacidad de operación cubre nuestras políticas favorables, entrega inmediata y segura, protección de privacidad y gran soporte',
'The mission of':'La misión de',
'is to provide you with the best products to the best prices':'es proveerte con los mejores productos al mejor precio',
'Our reputation, experience and keen industry insight permit us to negotiate low prices on the net':'Nuestra reputación, experiencia y conocimiento en la industria nos permite darte precios bajos en la red',
'If you have a suggestion you would like to share with our team, please let us know':'Si tienes cualquier sugerencia, puedes compartirla con nuestro equipo',
'Customer feedback shapes our business and allows us to better serve our audience so your ideas are always welcome':'Los comentarios de nuestros clientes dan forma a nuestro negocio y nos permiten dar un mejor servicio, por tanto, tus ideas son bienvenidas',
'respects your right to privacy':'respeta tus derechos de privacidad',
'Our goal is your complete satisfaction and we are not in the business of sharing your information with others':'Nuestro objetivo es tu completa satisfacción, no estamos en este negocio para compartir tu información con otros',
'All personal data is stored on our secure server with several layers of firewall protection':'Toda la información sensible se almacena en nuestros seguros servidores con protección Firewall',
'We promise to':'Te aseguramos',
'Provide 24/7 customer support on weekdays':'Proveerte un soporte continuo',
'Streamline the buying and paying process':'Un proceso de compra y pago fácil y fluido',
'Deliver goods to our customers with speed and precision':'Envío de productos con rapidez y precisión',
'Ensure the excellent quality of our products':'Excelencia en la calidad de nuestros productos',
'We hope our customers get a great experience buying our products':'Deseamos que nuestros clientes obtengan la mejor experiencia con la compra de nuestros productos',
'What shipping methods do you offer?':'¿Qué tipo de envíos hay?',
'The order will be sent directly to your address':'El pedido será enviado directamente a tu dirección',
'The shipping method is':'El tipo de envío es',
'The shipping methods available are':'Los tipos de envíos disponibles son',
'The delivery time is':'El tiempo de envío es',
'Flat rate shipping':'Envío modalidad básica',
'Standard rate shipping':'Envío estándar',
'Expedited rate shipping':'Envío urgente',
'days approx.':'días aprox.',
'The total shipping time is the order picking + handling time + shipping time':'El tiempo total de envío consta de la preparación del pedido + tiempo de manipulación + tiempo de envío',
'Normally, the processing time is very low':'Normalmente, el tiempo de preparación suele ser muy bajo',
'The shipping time can vary depending on the country':'El tiempo de envío puede variar en función del país',
'How do I calculate shipping costs?':'¿Cómo se calcula el coste de envío?',
'You will choose the shipping method on checkout':'Podrás elegir el tipo de envío en el carrito',
'The shipping cost is':'El coste de envío es',
'regardless of the products you buy':'independientemente de los productos que compres',
'The shipping cost will vary depending the shipping method you select':'El coste de envío variará en función del tipo de envío que selecciones',
'You can see it on checkout':'Podrás verlo más detalladamente en el carrito',
'The shipping cost will also vary depending on the weight of the products you add to cart':'El coste de envío también variará en función del peso de los productos que añadas al carrito',
'How can I track my package?':'¿Cómo puedo ver el estado de mi pedido?',
'If you choose the tracking number on checkout, you will get your tracking number and you will track':'Si eliges el número de seguimiento en el carrito, podrás conseguirlo y ver el estado de tu pedido',
'Do you ship to my country?':'¿Envías a mi país?',
'Do not worry! We send to worldwide':'¡No tienes de qué preocuparte! Enviamos a todo el mundo',
'Actually we send to':'Actualmente enviamos a',
'and':'y',
'If you do not find your county in the list, contact us':'Si no encuentras tu país en la lista, contacta con nosotros',
'If custom duties are incurred, who is responsible?':'Si aparecen costes de aduana, ¿Quién los asume?',
'It is the responsibility of the customer for any custom duty fees that may be charged upon delivery':'Los costes de aduana que puedan aparecer son responsabilidad del cliente',
'The import duty will depend of the custom policies of each country':'El cobro de aranceles dependerá de las políticas de aduana de cada país',
'If the Package held by Customs, who will be responsible for Package clearance?':'Si el paquete queda retenido por aduanas, ¿Quién se hará cargo?',
'If the items are detained by Customs after the shipment is done, the buyer is responsible for clearance of the detained items':'Si el paquete queda retenido por aduanas, el cliente será responsable',
'How do I change my shipping address?':'¿Cómo puedo cambiar mi dirección de envío?',
'If your order has been sent, you cannot change your shipping address. If the packet is not sent, contact us quickly':'Si tu pedido ya fue enviado, no se puede cambiar la dirección. Si aun no se ha enviado, contacta con nosotros rápidamente',
'Shipping methods':'Tipos de envío',
'Total weight':'Peso total',
'If your purchase is over':'Si tu compra es superior a',
'your shipping will be free!':'¡el envío será gratuito!',
'United States':'Estados Unidos',
'USA':'Estados Unidos',
'US':'Estados Unidos',
'China':'China',
'Japan':'Japón',
'Germany':'Alemania',
'France':'Francia',
'United Kingdom':'Reino Unido',
'Brazil':'Brasil',
'Italy':'Italia',
'Russia':'Rusia',
'India':'India',
'Canada':'Canadá',
'Australia':'Australia',
'Spain':'España',
'South Korea':'Corea del Sur',
'Mexico':'México',
'Indonesia':'Indonesia',
'Netherlands':'Holanda',
'Turkey':'Turquía',
'Switzerland':'Suiza',
'Sweden':'Suecia',
'Poland':'Polonia',
'Belgium':'Bélgica',
'Argentina':'Argentina',
'Austria':'Austria',
'Thailand':'Tailandia',
'South Africa':'Sudáfrica',
'Venezuela':'Venezuela',
'Colombia':'Colombia',
'Denmark':'Dinamarca',
'Malaysia':'Malasia',
'Singapore':'Singapur',
'Chile':'Chile',
'Hong Kong':'Hong Kong',
'Egypt':'Egipto',
'Philippines':'Filipinas',
'Greece':'Grecia',
'Finland':'Finlandia',
'Portugal':'Portugal',
'Ireland':'Irlanda',
'Peru':'Perú',
'Qatar':'Qatar',
'Ukraine':'Ucrania',
'New Zealand':'Nueva Zelanda',
'Romania':'Rumanía',
'Hungary':'Hungría',
'Puerto Rico':'Puerto Rico',
'Morocco':'Marruecos',
'Ecuador':'Ecuador',
'Cuba':'Cuba',
'Croatia':'Croacia',
'Luxembourg':'Luxemburgo',
'Guatemala':'Guatemala',
'Uruguay':'Uruguay',
'Andorra':'Andorra',
'How can I pay?':'¿Cómo puedo pagar?',
'You can pay on checkout when you add your product to shopping cart. We have two methods: Credit card and Paypal':'Puedes pagar en el carrito cuando añadas tus productos a la cesta. Tenemos dos formas de pago: Tarjeta de crédito y paypal',
'What credit cards do we accept?':'¿Qué tarjetas de crédito aceptamos',
'We accept the credit cards most used':'Aceptamos las tarjetas de crédito más usadas',
'Mastercard, Visa, American Express, Discover and Aurora':'Mastercard, Visa, American Express, Discover y Aurora',
'What advantages do I have if I pay with paypal?':'¿Qué ventajas tengo si pago con paypal?',
'You can get many advantages':'Puedes obtener muchas ventajas',
'Secure system and secure payments, buy and pay with your mobile or tablet, no membership fees or service charges, discount coupons':'Sistema seguro y pago seguro, compra y paga con tu móvil o tablet, sin comisiones, cupones de descuentos',
'We will try our best to make sure the products shipped to our customers are in good quality':'Vamos a intentar todo lo posible para que los productos enviados estén en el mejor estado posible',
'If there are some problems on the goods, you have right to guarantee your benefits':'Si hay algún problema con los productos, tienes derecho a reclamar',
'You do not have to worry about anything!':'¡No tienes que preocuparte por nada!',
'Return and refund':'Devolución del producto y reembolso',
'The products with quality problem can be returned and refund':'Los productos con problemas de calidad pueden ser devueltos y reembolsados',
'The customer will need to send the products back to us':'El cliente tendría que reenviarnos el producto',
'When we receive the products, we will give the refund':'Cuando recibbamos los producto, reenviaremos el reembolso',
'Loss':'Pérdida',
'If your packet has been sent but you do not receive the packet, the problem is the carrier':'Si tu paquete ha sido enviado pero no lo recibes, el problema es de la compañía de envíos',
'But we want to have satisfied customer':'Pero nosotros queremos clientes satisfechos',
'For that, if your packet is lost, we will refund your money or we will send again':'Por eso, si tu paquete se pierde, te devolveremos el dinero y te reenviamos otro',
'Products with quality problem can be returned and replaced':'Los productos con problemas de calidad pueden ser devueltos y reemplazados',
'Customer need to send the products back to us':'El cliente necesitaría reenviarnos el paquete',
'When we receive the products, we will replace new ones and ship back to customer':'Cuando nos llegue el paquete, lo reemplazaremos y lo enviaremos de nuevo',
'Replace':'Reemplazo',
'1.- INTRODUCTION':'1.- INTRODUCCIÓN',
'This document is intended to establish and regulate the terms of use and safeguarding the data of the site':'El presente documento tiene como finalidad el establecer y regular las normas de uso así como la salvaguardia de los datos del Sitio',
'(from now on called “the Site”) understanding that the site has all the pages and contents owned by':'(en adelante el "Sitio"), entendiendo por Sitio todas las páginas y sus contenidos propiedad de',
'which is accessed through the domain':'a las cuales se accede a través del dominio',
'The use of this site as well as the services it offers to the user, implies full and unreserved acceptance of each and every one of the conditions contained in this Legal Notice (from here on "General Conditions ")':'La utilización de esta página, así como de los servicios que en ella se pone a disposición del usuario, supondrá la aceptación plena y sin reservas de todas y cada una de las condiciones generales recogidas en la presente Información Legal (en adelante las "Condiciones Generales")',
'so the user should be aware of the importance of reading them each time the user visits the Site':'por lo que el usuario deberá de ser consciente de la importancia de leerlas cada vez que visite el Sitio',
'Accessing the Site implies knowing and  accepting the following "General Conditions" which':'El acceso al Sitio implica el conocimiento y aceptación de las siguientes "Condiciones Generales" que',
'recommends the users to print or download and read  carefully each time the user accesses the Site':'recomienda al usuario su impresión o su descarga y lectura detallada cada vez que acceda al Sitio',
'2.-GENERAL INFORMATION':'2.-INFORMACIÓN GENERAL',
'In compliance with the duty to inform the customer contained in Article 10 of Law 34/2002, of July 11, of the Society Services of the Information  and Electronic Commerce, below we reflect the following':'En cumplimiento con el deber de información recogido en artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y del Comercio Electrónico, a continuación se reflejan los siguientes datos',
'is an entity from':'es una entidad de',
'The email contact is':'El email de contacto es',
'and the telephone':'y el teléfono',
'3. - USE OF THE SITE':'3. - USO DEL SITIO',
'By accepting these Terms the user agrees to use the Website and the services it provides in the way, the manner and form in which it is established':'Mediante la aceptación de las presentes Condiciones Generales el usuario se compromete a usar el presente Sitio y los servicios puestos a su disposición en el mismo, de la manera y en la forma que en él mismo se establece',
'Users may not use this Site and its services for illegal and / or contrary purposes against those  stated in the General Conditions, which may be detrimental to the rights and / or interests of others or in any way damage the Site preventing it or its present and future services to work':'Quedando obligado a no utilizar el presente Sitio y sus servicios con fines ilícitos y/o contrarios a los fines establecidos en estas Condiciones Generales, que pudieran ser lesivos de derechos y/o intereses de terceros o que de cualquier forma puedan dañar el presente Sitio o impedir su correcto funcionamiento o de los servicios que en él se ofrecen u ofrecieran en el futuro',
'4.- SCOPE OF THE SITE. USER RESPONSIBILITY':'4.- ÁMBITO DEL SITIO. RESPONSABILIDAD DEL USUARIO',
'The access to this site is the sole responsibility of the users. That includes any risks arising from the use of the Site':'El acceso a este Sitio es responsabilidad exclusiva de los usuarios. Los riesgos derivados de la utilización del Sitio por el usuario serán a su único y exclusivo cargo. No es objeto de garantía por parte de el Sitio',
'does NOT guarantee':'NO se responsabiliza',
'(I) The infallibility, availability, continuity, absence of defects or safety of the Site':'(I) La infalibilidad, la disponibilidad, la continuidad, la inexistencia de deficiencias y la seguridad del Sitio',
'(II) The content of the Site or the information passing through it are free of viruses or other harmful elements such as errors, omissions or inaccuracies':'(II) Que el contenido del Sitio o la información que pasa a través de él esté libre de virus o de otros elementos lesivos así como de errores, omisiones o incorrecciones',
'(III) The safety of the user of the Website; The size not be liable for any loss or damage that may arise from interferences, omissions, interruptions, computer viruses, telephone faults or disconnections in the operational functioning of this electronic system , due to causes unrelated to the Site, the delays or blockages in the use of this electronic system caused by deficiencies or overloading in the data processing Centre, telephone lines, in the Internet system or other electronic systems, nor damage that may be caused by third parties through illegalities beyond the control of the Site':'(III) La seguridad en la utilización que el usuario haga del Sitio; El Sitio no será responsable de posibles daños o perjuicios que se pudieran derivar de interferencias omisiones, interrupciones, virus informáticos, averías telefónicas o desconexiones en el funcionamiento operativo de este sistema electrónico, motivadas por causas ajenas a el Sitio; de retrasos o bloqueos en el uso del presente sistema electrónico causados por deficiencias o sobrecargas en su Centro de Procesos de Datos, de líneas telefónicas , en el sistema de Internet o en otros sistemas electrónicos; ni tampoco de daños que puedan ser causados por terceras personas mediante intromisiones ilegítimas fuera del control del Sitio',
'It also exempts the Site from liability for any loss or damage incurred by you as a result of errors, defects or omissions in the information provided by the Site provided from outside sources':'Asimismo, se exonera a el Sitio de responsabilidad ante cualquier daño o perjuicio que pudiera sufrir el usuario como consecuencia de errores, defectos u omisiones, en la información facilitada por el Sitio siempre que proceda de fuentes ajenas',
'Mere access to the Site does not imply any kind of commercial relationship between the user and the Site':'El mero acceso a este Sitio no supone entablar ningún tipo de relación de carácter comercial entre el Sitio y el usuario',
'5.- UPDATING AND MODIFICATION OF INFORMATION':'5.- ACTUALIDAD Y MODIFICACIÓN DE LA INFORMACIÓN',
'The information on this site is accurate at the date of the last update. The Site reserves the right to update, modify or delete information on this Site, and may limit or deny access. The Site reserves the right to make, at any time, changes and modifications deemed desirable, and may exercise this right at any time and without notice':'La información que aparece en este Sitio es la vigente en la fecha de su última actualización. El sitio se reserva el derecho a actualizar, modificar o eliminar la información de este Sitio, pudiendo limitar o no permitir el acceso al mismo. El sitio se reserva la facultad de efectuar, en cualquier momento, cuantos cambios y modificaciones estime convenientes, pudiendo hacer uso de tal facultad en cualquier momento y sin previo aviso',
'6.- CONTENTS':'6.- CONTENIDOS',
'The Site does not guarantee, or accepts responsibility for the consequences that may result from errors in the contents appearing on the Site provided by others. The Site is not responsible in any way for the contents, commercial activities, products and services that can be viewed through electronic links (links) if there were any, and if there were, directly or indirectly, through this Site':'El Sitio no garantiza, ni se responsabiliza de las consecuencias que pudieran derivarse de los errores en los contenidos que pudieran aparecer en este Sitio proporcionados por terceros. El Sitio no se responsabiliza en modo alguno de aquellos contenidos, actividades comerciales, productos y servicios incluidos que pudiesen visualizarse mediante enlaces electrónicos (links) si los hubiera y cuando los hubiere, de forma directa o indirectamente, a través de este Sitio',
'The presence of links in the the Site Website, unless expressly stated otherwise, is for informational purposes only and in no way a suggestion, invitation or recommendation thereof. These links do not represent any kind of relationship between the Site and companies or owners of the websites that can be accessed through these links. The Site reserves the right to withdraw unilaterally and at any time and without notice the link from its Site':'La presencia de links en el Sitio de el Sitio, salvo manifestación expresa en contrario, tiene una finalidad meramente informativa y en ningún caso supone sugerencia, invitación o recomendación sobre los mismos. Estos enlaces no representan ningún tipo de relación entre el Sitio y las empresas o particulares titulares de los sitios webs a los que puede accederse mediante estos enlaces. El Sitio se reserva el derecho de retirar de modo unilateral y en cualquier momento y sin previo aviso los enlaces que pudieran aparecer en su Sitio',
'The Site reserves the right to prevent or prohibit access to the Site to any Internet user to enter this site any content contrary to legal or moral standards, reserving the right to pursue legal action it deems necessary to prevent such behaviours':'El Sitio se reserva el derecho a impedir o prohibir el acceso al Sitio a cualquier usuario de Internet que introduzca en este Sitio cualquier contenido contrario a las normas legales o sea inmoral, reservándose el derecho de ejercer las medidas legales que estime oportunas para evitar este tipo de conductas',
'7.- NAVIGATION, ACCESS AND SECURITY':'7.- NAVEGACIÓN, ACCESO Y SEGURIDAD',
'The Site Central makes every effort to ensure that browsing takes place under optimum conditions and to avoid any type of damage that may occur during the same. The Site is not liable for damages of any kind that may be caused to users by using other browsers or different versions of the browsers for which the Site is designed':'Central de El Sitio realiza los máximos esfuerzos para que la navegación se realice en las mejores condiciones y evitar los perjuicios de cualquier tipo que pudiesen ocasionarse durante la misma. El Sitio no se hace responsable de los perjuicios, de cualquier índole, que pudieran ocasionarse a los usuarios por la utilización de otros navegadores o versiones distintas de los navegadores para los que ha sido diseñado el Sitio',
'The Site makes no representation or guarantee that access to this Site will be uninterrupted or error free. No responsibility or guarantee that the content or software that can be accessed through this site is free from error or cause damage. The Site, in no event, can be liable for any losses or damages of any kind arising from the access and use of the Site, including but not limited to damage to systems or those caused by a virus':'El Sitio no se responsabiliza ni garantiza que el acceso a este Sitio sea ininterrumpido o que esté libre de error. Tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a través de este Sitio, esté libre de error o cause un daño. En ningún caso el Sitio será responsable por las pérdidas, daños o perjuicios de cualquier tipo que surjan por el acceso y el uso del Sitio, incluyéndose pero no limitándose, a los ocasionados a los sistemas informáticos o los provocados por la introducción de virus',
'The Site is not responsible for any damage that may be caused to users by improper use of this Site. In particular, is not responsible in any way for breakdowns, interruptions, faults or defects in telecommunications that may occur. The services offered on the Site may only be used correctly if they meet the technical specifications for which it was designed':'El Sitio no se hace responsable de los daños que pudiesen ocasionarse a los usuarios por un uso inadecuado de este Sitio. En particular, no se hace responsable en modo alguno de las caídas, interrupciones, falta o defecto de las telecomunicaciones que pudieran ocurrir. Los servicios ofertados en este Sitio sólo pueden ser utilizados correctamente si se cumplen las especificaciones técnicas para las que ha sido diseñado',
'8.- DATA PROTECTION':'8.- PROTECCIÓN DE DATOS',
'The processing of personal data and sending electronic communications are regulated by  the rules established in the Organic Law':'El tratamiento de los datos personales y el envío de comunicaciones por medios electrónicos están ajustados a la normativa establecida en la Ley Orgánica15/1999,13 de Diciembre, de Protección de Datos de Carácter Personal (B.O.E.14/12/1999) y en la Ley 34/2002, de 11 de Julio, de Servicios de la Sociedad de la información y de Correo Electrónico (B.O.E.12/07/2002)',
'In accordance with the provisions of the current legislation on data protection, we inform you that your personal data will be incorporated into the Site Personnel Selection file in order to have your professional history for selection and contractual purposes':'De acuerdo con lo dispuesto en la legislación vigente en materia de protección de datos, te informamos de que tus datos personales serán incorporados al fichero de Selección de Personal de el Sitio con la finalidad de contar con tu historia profesional para desarrollar las funciones de selección y contratación',
'Also, unless stated otherwise, the Site and any of the Companies that make up the Site, shall have access to your personal information, solely for the purposes described above. The Site guarantees the right to access, rectify, cancel and object to the processing of data which must be notified in writing':'Asimismo, salvo oposición expresa al respecto, tendrán acceso a tus datos personales cualquiera de las Empresas que conforman el Sitio, exclusivamente con las finalidades descritas anteriormente. El Sitio garantiza el ejercicio de los derechos de acceso, rectificación, cancelación y oposición escrita',
'If after one year from the inclusion of your personal data you have not heard from us, we will proceed to erase the data from our file':'Si pasado un año desde la inclusión de tu currículo no has tenido noticias nuestras, procederemos al borrado de los datos de nuestro fichero',
'9.- USE OF COOKIES':'9.- USO DE COOKIES',
'Access to the Website may imply the use of cookies on its pages and those pages linked or referenced through links. Users who do not wish to receive cookies or want to be informed of their use may configure your browser accordingly':'El acceso a este Sitio puede implicar la utilización de cookies, tanto en sus páginas como en las enlazadas o referenciadas mediante links. Aquellos usuarios que no deseen recibir Cookies o quieran ser informados de su fijación pueden configurar su navegador a tal efecto',
'10.- INTELLECTUAL PROPERTY AND COPYRIGHT':'10.- PROPIEDAD INTELECTUAL Y DERECHOS DE AUTOR',
'The Site declares that unless otherwise indicated in the Site, text, images, illustrations, designs, icons, photographs, video clips, sound clips and other materials found on the Site and any other intellectual creations and / or inventions or scientific and technical discoveries, whatever their commercial or industrial application (from here on  collectively named "Content") have been created or invented by the Site or transferred, licensed, transmitted or authorized by the owners and / or assignees':'El Sitio declara que salvo que se indique lo contrario en el Sitio, los textos, imágenes, ilustraciones, diseños, iconos, fotografías, segmentos de vídeo, segmentos de sonido y demás materiales que se encuentren en el Sitio y cualesquiera otras creaciones intelectuales y/o invenciones o descubrimientos científicos y técnicos, cualquiera que sea su aplicación empresarial o industrial (en adelante colectivamente denominados el "Contenido") han sido creados o inventados por el sitio o cedidos, licenciados, transmitidos o autorizados a ésta por sus titulares y/o cesionarios',
'The User agrees not to remove or alter any distinctive sign used on the Site, including, but not be limited, brand names, trademarks (graphics, logos, etc), the "copyright" and other data identifying the rights of the Site or third parties on the Website':'El Usuario se compromete a no suprimir o alterar cualesquiera signo distintivo utilizado en el Sitio, tales como, con carácter no exhaustivo, marcas, nombres comerciales (gráficos, logotipos, etc), el "copyright" y demás datos identificativos de los derechos de el Sitio o de terceros titulares incorporados en el Sitio',
'The Site own all rights over any works, inventions, discoveries, patents, ideas, concepts, updates and improvements related to the Site,  systems, applications and programs or services provided by the Site, which are created , made, developed or implemented first by the Site either alone or with the help of users of the Site, during or as a result of a design, development or other activity performed in accordance with the Contract':'Son propiedad de el Sitio igualmente todos los derechos sobre cualesquiera obras, inventos, descubrimientos, patentes, ideas, conceptos, actualizaciones y las mejoras relacionadas con el Sitio, sus sistemas, aplicaciones y programas o con los servicios que el Sitio presta, que sean creados, realizados, desarrollados o puestos en práctica por primera vez por el Sitio ya sea por sí sola o con la ayuda de los usuarios del Sitio, en el transcurso o como resultado de algún diseño, desarrollo o cualquier otra tarea realizada de conformidad con el Contrato',
'You may not use the name, trademarks, symbols, logos or distinctive signs of ownership by the Site without the express written consent of the latter':'El Usuario no podrá utilizar el nombre ni las marcas, símbolos, logos o signos distintivos de titularidad de por el Sitio sin el consentimiento expreso y escrito de ésta',
'In the event that any user or third party considers that any of the content on the site is in violation of copyright or other rights of intellectual property protection, please notify us at':'En caso de que cualquier usuario o tercero considere que cualquiera de los contenidos existentes en la Sitio suponga una violación de los derechos de autor u otros derechos de protección de la propiedad intelectual, rogamos que lo comunique a',
'11.- JURISDICTION AND LAW':'11.- JURISDICCIÓN Y LEGISLACIÓN APLICABLE',
'The Terms of Use that are in this Agreement are governed by law. Both the Site and the users of the Site agree that any dispute that may arise regarding the interpretation, compliance and / or enforcement of these rules shall be subject to the jurisdiction of the Courts and Tribunals , with expressly waive any other jurisdiction that may correspond':'Las Normas de Uso que se encuentran en el presente Acuerdo Legal, se rigen por la ley. Tanto el Sitio como los usuarios del Sitio están de acuerdo en que para cualquier discrepancia que pueda surgir en cuanto a la interpretación, cumplimiento y/o ejecución, de las presentes normas se someterán expresamente a la jurisdicción de los Jueces y Tribunales competentes, con renuncia expresa, a cualquier otro fuero que pudiera corresponderles',
'Euro':'Euro',
'US dollar':'Dólar estadounidense',
'Pound sterling':'Libra esterlina',
'Management':'Administración',
'Product in stock':'Producto en stock',
'Create product':'Crear producto',
'Overview':'Visión general',
'Products':'Productos',
'Pages':'Páginas',
'Stats':'Estadísticas',
'Layout':'Diseño',
'Template':'Plantilla',
'Settings':'Configuración',
'Images':'Imágenes',
'Sign out':'Cerrar sesión',
'Prev':'Anterior',
'Next':'Siguiente',
'Name':'Nombre',
'Email':'Email',
'Message':'Mensaje',
'Send':'Enviar',
'Please, insert a correct email':'Por favor, inserta un email correcto',
'Please, write a message':'Por favor, escribe un mensaje',
'Your message has been sent. Thanks!':'Tu mensaje ha sido enviado. ¡Gracias!',
'Through the following contact form':'A través del siguiente formulario de contacto',
'Edit notes':'Editar notas',
'Unique size':'Talla única',
'One size':'Talla única',
'Accessories':'Accesorios',
'Bags backpacks and wallets':'Maletas, bolsos y carteras',
'Corsets and bustiers':'Corsets',
'Dresses':'Vestidos',
'Heels boots and sandals':'Tacones, botas y sandalias',
'Jackets and coats':'Chaquetas y abrigos',
'Leggings and pantyhose':'Leggings',
'Pants and jeans':'Pantalones y vaqueros',
'Shirts polo shirts and blouses':'camisas, polos y blusas',
'Shoes and sneakers':'zapatos y zapatillas',
'Skirts':'Faldas',
'Suits and blazers':'Trajes y americanas',
'Sweaters and hoodies':'Sudaderas y suéteres',
'Tees long sleeves and tops':'Camisetas de manga corta, larga y asillas',
"Main dh diamond horn tee":"Camiseta main dh diamond horn",
"Sexy girl diamond horn tee":"Camiseta sexy girl diamond horn",
"Audio cassette diamond horn tee":"Camiseta audio cassette diamond horn",
"Tees; long sleeves and tops":"Camisetas de manga corta; larga y asillas",
"MMA division tee":"Camiseta MMA division",
"Defeat thy rivals tee":"Camiseta Defeat thy rivals",
"Extreme cage fighter tee":"Camiseta Extreme cage fighter",
"Mixed marcial arts tee":"Camiseta Mixed marcial arts",
"Training to be a cage fighter tee":"Camiseta Training to be a cage fighter",
"MMA fighter tee":"Camiseta MMA fighter",
"Mixed marcial arts tee":"Camiseta Mixed marcial arts",
"Cage fighter tee":"Camiseta Cage fighter",
"Bushido MMA tee":"Camiseta Bushido MMA",
"Brooklyn boxing gym tee":"Camiseta Brooklyn boxing gym",
"Bojewoje sambo tee":"Camiseta Bojewoje sambo",
"Mma Full contact fighter warriors long sleeves":"Camiseta de manga larga Mma Full contact fighter warriors",
"New zealand all black long sleeves":"Camiseta de manga larga New zealand all black",
"Rugby athletic train long sleeves":"Camiseta de manga larga Rugby athletic train",
"Hardcore cage fighting long sleeves":"Camiseta de manga larga Hardcore cage fighting",
"Cage fighter mma fight to the end tee":"Camiseta Cage fighter mma fight to the end",
"Mma fight division bulldog tee":"Camiseta Mma fight division bulldog",
"Muay thai the art of fighting tee":"Camiseta Muay thai the art of fighting",
"Mma fighter warrior spirit tee":"Camiseta Mma fighter warrior spirit",
"Mixed marcial arts fight with honor tee":"Camiseta Mixed marcial arts fight with honor",
"Mma fighter training discipline respect tee":"Camiseta MMA fighter training discipline respect",
"Jiu jitsu red cover tee":"Camiseta Jiu jitsu red cover",
"Cage fighter don't give up the fighter tee":"Camiseta Cage fighter don't give up the fighter",
"Mma fighters tee":"Camiseta MMA fighters",
"Full contact mma tee":"Camiseta Full contact MMA",
"Full contact mixed martial arts tee":"Camiseta Full contact mixed martial arts",
"Muay thai full contact tee":"Camiseta Muay thai full contact",
"Hard knocks boxing gym tee":"Camiseta Hard knocks boxing gym",
"Born 2 be a boxer tee":"Camiseta Born 2 be a boxer",
"Invincible tee":"Camiseta Invincible",
"Jiu-jitsu tee":"Camiseta Jiu-jitsu",
"MMA Mixed marcial arts tee":"Camiseta MMA Mixed marcial arts",
"Urban fighters tee":"Camiseta Urban fighters",
"Ultimate fight dept. tee":"Camiseta Ultimate fight dept.",
"Seek and destroy tee":"Camiseta Seek and destroy",
"Rocky balboa boxing gym tee":"Camiseta Rocky balboa boxing gym",
"Primus pilus mma tee":"Camiseta Primus pilus MMA",
"The newspaper tee":"Camiseta The newspaper",
"Muay thai boxing tee":"Camiseta Muay thai boxing",
"This store is configured to be able to purchase and ship your items to somewhere in the world. Do you live in US, Brazil, Australia, Europe...? Are you going on vacation and you want it delivered? No Problem! We'll send it!":"Esta tienda está configurada para poder comprar y enviar tu producto a cualquier parte del mundo. ¿Vives en Estados Unidos, América latina, España? ¿Vas a irte de vacaciones y quieres que te lo enviemos? ¡No hay problema! Te lo enviaremos.",
"Use our shipments!":"¡Usa nuestros envíos!",
"Don't risk!":"¡No te arriesgues!",
"We have the best satisfaction policy. If your packet is lost or you receive a defective product, we will refund your money immediately. Don't risk buying at other stores and losing your money. Here your order is secure. Try it!":"Tenemos la mejor política de satisfacción. Si tu paquete se perdió o recibiste un producto defectuoso, te reembolsaremos el dinero inmediatamente. No arriesgues comprando en otras tiendas y perdiendo tu dinero. Aquí tu pedido es seguro. ¡Pruébalo!",
"Not disappoint!":"¡No te defraudará!",
"The best spanish brand: 'Diamond horn'":"La marca española: 'Diamond Horn'",
"We are glad for to present you a cool clothing brand: 'Diamond horn'. They bring a magnific collection of nice products. We are the only one authorized dealer. You will not find these products anywhere else. Are you going to let it go?":"Nos enorgullece presentarte una gran marca de ropa: 'Diamond horn'. Ellos nos traen una magnífica colección de muy buenos productos. Somos los únicos distribuidores autorizados. No encontrarás estos productos en ningún otro sitio. ¿Vas a dejarlo escapar?",
"Take advantage!":"¡Aprovécha!",
"Page not found":"Página no encontrada",
"You will be redirected to the homepage.":"Serás redireccionado a la página principal.",
"No results":"Sin resultados",
"Description":"Descripción",
"Category":"Categoría",
"Brand":"Marca",
"Features":"Características",
"Type":"Tipo",
"Colors":"Color",
"Empty cart":"Vaciar el carrito",
"Specifications":"Especificaciones"
}
